remote_theme: mmistakes/so-simple-theme@3.2.0
locale: en-US
title: ClearScript
title_image: /ClearScript7-ReadMe.png
title_image_scale: 0.75
copyright: Â© 2022 Microsoft Corporation. Powered by [Jekyll](https://jekyllrb.com) & [So Simple](https://github.com/mmistakes/so-simple-theme).
description: Add scripting to your .NET applications quickly and easily.
url: https://clearscript.clearfoundry.net
baseurl: ""
logo: /ClearScriptLogo.png
skin: /assets/css/skins/light.css
read_time: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
paginate: 5
paginate_path: /page:num/
search_full_content: true
author:
  name: ClearScript Library
  picture: /ClearScript.png
  email: ClearScript@microsoft.com
  twitter: ClearScriptLib
  links:
  - title: Twitter
    url: https://twitter.com/ClearScriptLib
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/ClearScriptLib
    icon: fab fa-github-square
  - title: Email
    url: mailto:ClearScript@microsoft.com
    icon: fas fa-envelope-square
footer_links:
  - title: Twitter
    url: https://twitter.com/ClearScriptLib
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/microsoft/ClearScript
    icon: fab fa-github-square
  - title: Email
    url: mailto:ClearScript@microsoft.com
    icon: fas fa-envelope-square
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square
